# config for the welcome-bot
newIssueWelcomeComment: |
  Thanks for opening your first issue here! ğŸ’–

# Be sure to follow the issue template.
# Then the issue will be worked on in no time. ğŸ‘
# Comment to be posted on PRs from first time contributors in your repository
newPRWelcomeComment: |
  Thanks for opening a pull request! ğŸ’–
  Please check out the [code of conduct](https://github.com/kai-tub/ben-docs//blob/main/.github/CODE_OF_CONDUCT.md) and the [contributing guidelines](https://github.com/kai-tub/ben-docs//blob/main/.github/CONTRIBUTING.md).
  Although, you probably have read it already. ğŸ˜
# Comment to be posted on PR merges from first time contributors in your repository
firstPRMergeComment: |
  Congrats on merging your first pull request! ğŸ‰ğŸ‰ğŸ‰
  We are proud of you and your accomplishment ğŸ†.

  ![thanks-for-pr-image](https://github.com/kai-tub/ben-docs//blob/main/.github/thanks_for_pr.jpg)
